app = "线上讲座系统"
listenAddr = "0.0.0.0:8000"
baseURL = "http://127.0.0.1:8000"
agreement = [
    "线上讲座系统用户使用协议",
    "如果你使用本系统，则表示你同意本协议",
    "线上讲座系统是教务处学工部发起，杭电助手开发、维护的系统，以下称线上讲座系统为本系统",
    "本系统仅限杭电师生使用",
    "我们会尽最大努力保证本系统正常使用"
]

[database]
user = "root"
password = "123456"
addr = "tcp(127.0.0.1:3306)"
db = "lecture"
[unit]
"01" = "机械工程学院"
"03" = "管理学院"
"04" = "电子信息学院"
"05" = "计算机学院"
"06" = "自动化学院"
"07" = "理学院"
"08" = "通信工程学院"
"09" = "信息工程学院"
"10" = "软件工程学院"
"11" = "外国语学院"
"12" = "人文与法学院"
"13" = "体育教学部"
"14" = "会计学院"
"15" = "经济学院"
"16" = "先进技术研究院、国防科技研究院"
"17" = "国际教育学院"
"18" = "卓越学院、创新创业学院"
"19" = "生命信息与仪器工程学院"
"20" = "材料与环境工程学院"
"22" = "数字媒体与艺术设计学院"
"23" = "马克思主义学院"
"24" = "浙江保密学院"
"25" = "工程研究院"
"26" = "浙江高等教育研究院"
"27" = "网络空间安全学院、浙江保密学院"
"31" = "继续教育学院、继续教育管理中心"